options:
  updateFrequency: 1000
  stateGetter: plugins.builtin_stategetters.AutomaticToggleGetter
states:
- deploying:
    text: 'Deploying, mfer'
    title: 'Deploy'

- deploying_complete
- testing
- testing_complete
- idle
#- magnus:  progression